server:
  port: 8080

woyou:
  baseurl: http://www.baidu.com


spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8

#mybatis-plus:
#  mapper-locations:
#    -
